# Generated by Django 4.1.1 on 2022-09-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unityemail',
            name='name',
        ),
    ]
